### ISSUE TITLE
裁判文书相关的测试集问题

### ISSUE THREAD

**Issue by YanShuang17** [MozerWang/Loong#10]
作者您好，我在分析评测样本时，发现裁判文书作为context的测试样本中，大部分问题都是以案由为筛选条件的，但是所提供的context中，每份裁判文书均没有显式提供案由信息，是bug还是其他原因呢？ @MozerWang

**Comment by MozerWang** [comment]
The detailed information can be found in the file located at doc/legal/legal.json. The 'content' within each Dict corresponds to the case you mentioned.
