### ISSUE TITLE
How to get markdown text of papers

### ISSUE THREAD

**Issue by likuanppd** [MozerWang/Loong#11]
Hello authors,

Loong is a great work. I notice that papers in the dataset are in markdown style, and you mention that they are collected from arxiv. So could you please tell me how can I get papers in markdown format?

Thx.

**Comment by MozerWang** [comment]
We recommend using the [Mathpix tool](https://mathpix.com/) for PDF parsing (it works well but requires payment). When processing, we removed the appendix sections.
