### ISSUE TITLE
Error in running 'sh vllm_example.sh'

### ISSUE THREAD

**Issue by SetonLiang** [MozerWang/Loong#12]
```
python -m vllm.entrypoints.openai.api_server \
--served-model-name Llama-3.1-8B-Instruct \
--model "meta-llama/Llama-3.1-8B-Instruct/" \
--tensor-parallel-size=4 \
--trust-remote-code 
```
I want to deploy the llama model, but when running this script in vllm_example.sh, it will generate an error (outlines=0.1.11, vllm=0.5.0.post1):
ImportError: cannot import name 'build_regex_from_schema' from 'outlines.fsm.json_schema' (/home/anaconda3/envs/Finance_Baseline/lib/python3.9/site-packages/outlines/fsm/json_schema.py)
How to solve this problem?

**Comment by MozerWang** [comment]
I think this error is about vllm's environment and version. You could try another version of vllm (e.g. vllm==0.6.2).

**Comment by MozerWang** [comment]
Or you can try another script to use vllm openai sever.  Please refer to https://docs.vllm.ai/en/stable/serving/openai_compatible_server.html#

**Comment by SetonLiang** [comment]
Thanks, it was indeed a version issue with vllm. The version of vllm in the requirements.txt file was **vllm==0.5.0.post1**. When I updated it to version 0.5.3.post1, it worked.

**Comment by SetonLiang** [comment]
```
def get_api_results(prompt_input, config):
    prompt = prompt_input['prompt']

    if config['type'] == 'openai' or config['type'] == 'vllm':
        client = OpenAI(api_key=config['args']['api_key'],
                        base_url=config['args']['api_url'] if config['args']['api_url']!='' else None)
        try: 
            response = client.chat.completions.create(
                messages=[{"role": "user","content": prompt}],
                model=config['args']['api_name'],
                temperature=config['run_args']['temperature']
            )
            return response.choices[0].message.content
        except Exception as e:
                print(e)
                return []
```
When I run this code in **step2_model_generate.py**, the following error occurs:
TypeError: __init__() got an unexpected keyword argument 'proxies'.

I would like to know how to resolve this issue?

**Comment by SetonLiang** [comment]
After I upgraded the OpenAI version, it ran normally. However, it is encountering some connection errors as shown in the following figure. Is this normal?
![image](https://github.com/user-attachments/assets/38a0927d-4dfe-42ed-a7a3-d9213fdcc642)

**Comment by MozerWang** [comment]
It is normal, which is about the Openai's request error.

**Comment by SetonLiang** [comment]
However, there is an issue: even after successfully loading LLama-3.1-8B-instruct, it still seems unable to connect.
![image](https://github.com/user-attachments/assets/4488022d-5338-489a-aa46-eec7b07e57dd)

When running the following instruction
```
curl http://localhost:8000/v1/completions \
    -H "Content-Type: application/json" \
    -d '{
        "model": "Llama-3.1-8B-Instruct",
        "prompt": "San Francisco is a",
        "max_tokens": 7,
        "temperature": 0
    }'
```
it will cause "curl: (7) Failed to connect to localhost port 8000 after 0 ms: Could not connect to server"

When running **step2_model_generate.py**, the connection error above causes the generated answer to be empty.
![image](https://github.com/user-attachments/assets/38adcb26-1f77-440d-a58d-9b0e2a54e9d6)

**Comment by MozerWang** [comment]
Sorry, I made a mistake. 

It looks like the error was caused by the request to vllm server. This is not the bug existed in step2_model_generate.py. To solve this, I think you can first try to run vllm openai server request successfully. (Check out your key\port\model_name carefully). Please refer to the instruction from https://docs.vllm.ai/en/stable/serving/openai_compatible_server.html#. 

If you still have questions, please let me know

**Comment by SetonLiang** [comment]
When running **step2_model_generate.py**, a **Request timeout** issue often occurs (the first timeout appears on the third data item), as shown in the figure below.
![image](https://github.com/user-attachments/assets/40ad32d0-419b-463f-8a15-035ad2817c0e)

Setting timeout and proxy did not resolve the issue. How can this problem be solved?

**Comment by MozerWang** [comment]
The context length may be too long to decode. Could you set a higher timed-out value? 

You can also refer to some practice about using llama3.1 on long-context modeling.

**Comment by SetonLiang** [comment]
Thanks! But I really want to know how you use Llama 3.1 to generate responses to form the following leaderboard, especially on set3 and set4. The reasoning method for long-context does not seem to be reflected in the code.
![image](https://github.com/user-attachments/assets/27425503-154e-4fd0-8ec9-c242837bc172)

**Comment by MozerWang** [comment]
Same experiment setup as other llms without any additional reasoning methods.

**Comment by SetonLiang** [comment]
So it won't cause the 'Request time out' issue, especially when you run with the llama3.1 based on the same code?
```
if config['type'] == 'openai' or config['type'] == 'vllm':
        client = OpenAI(api_key=config['args']['api_key'],
                        base_url=config['args']['api_url'] if config['args']['api_url']!='' else None)
        try: 
            response = client.chat.completions.create(
                messages=[{"role": "user","content": prompt}],
                model=config['args']['api_name'],
                temperature=config['run_args']['temperature']
            )
            return response.choices[0].message.content
        except Exception as e:
                print(e)
                return []
```

**Comment by MozerWang** [comment]
Yes. There is no more code specifically used. I used 4 * A100 80G (tensor parallel = 4) to run llama3.1-8b.

**Comment by SetonLiang** [comment]
OK, thanks. Another question is about the RAG part. I noticed that the RAG part was mentioned in the paper, but it doesn't seem to be reflected in the code. So, is there no code for the RAG part?
If not, does RAG involve embedding, chunking, and retrieval of the docs for each piece of data in the dataset?
![image](https://github.com/user-attachments/assets/09a2928d-4916-4b40-9ef2-c8af2c63376c)
For example, when evaluating this piece of data, is retrieval and augmentation performed on its relevant documents, or on the entire corpus?

**Comment by MozerWang** [comment]
Yes, the RAG is the vanilla implementation, which is only performed on the relevant or mentioned documents in each test case.

**Comment by SetonLiang** [comment]
Sorry to bother you again. I might have one more question regarding inference. You mentioned that running llama3.1-8b on 4 * A100 80G (tensor parallel = 4) works fine, but does the inference effect differ on different GPUs with the same model? I am running it on 4 * 4090 24G (tensor parallel = 4), but I encounter request timeout issues.

Also, with the context window size set to 128k, can Llama3.1 really support inference for long texts at set3 and set4 levels?

**Comment by MozerWang** [comment]
Yes. Request timeout issues are related to your device and the vllm config, not the code.  For the last question, definitely yes.

If these help you, I would appreciate it if you could give the repo a star.
