### ISSUE TITLE
What is the response generation time for different models?

### ISSUE THREAD

**Issue by SetonLiang** [MozerWang/Loong#13]
Could you tell me the response generation time on the total dataset for different models, particularly for **llama3.1-8B-Instruct**?

**Comment by MozerWang** [comment]
For small sizes (7b,8b), it costs nearly 3 hours, including inference and evaluation, on 4*A100 80G.

**Comment by MozerWang** [comment]
For small sizes (7b,8b), it costs nearly 2 hours, including inference and evaluation, on 4*A100 80G.
