### ISSUE TITLE
what does the "level" mean when calculate metrics

### ISSUE THREAD

**Issue by yinpeisu** [MozerWang/Loong#3]
for set in [1,2,3,4]:
        print(f"------------------ Set {set} metrics ------------------")
        for level in [1,2,3,4]:
            cal_metric(args, tag="eval_response", set=set, level=level)

**Comment by MozerWang** [comment]
Thanks for your advice！

it means task：level1 = Spotlight Locating，level2 = Comparison，level3 = Clustering，level4 = Chain of Reasoning

We will add relevant instructions in the readme.
