### ISSUE TITLE
How to reproduce the results in the leaderboard?

### ISSUE THREAD

**Issue by cizhenshi** [MozerWang/Loong#6]
During the evaluation process, I noticed that the models have different lengths, such as qwen-128, and the length is measured using the tokenizer of gpt-3.5-turbo. For qwen 128k, should it be set as 128k in the configuration? Similarly, should kimi be set to 200k?

**Comment by cizhenshi** [comment]
MAX_LENGTH="256000" # According to the context window of llm. The value of config takes precedence
for qwen 128k it should be 128k？
for kimi  is should be 200k?

Is my understanding correct?

**Comment by MozerWang** [comment]
Thank you for your attention to our work.

Considering the different compression rates of various tokenizers and reserving a portion of the length for output, we recommend setting the MAX_LENGTH of the 128K model to 110K and the MAX_LENGTH of the 200K model to 190K.
